### ISSUE TITLE
BP Reordering using large amounts of memory

### ISSUE THREAD

**Issue by JMMackenzie** [pisa-engine/pisa#423]
- BP seems to be using much more memory (up to 4x more from my calculations) than it did before, and can even end up crashing if the depth is too deep or if the collection is large. 

- My working hypothesis is that the introduction of the `thread_local` storage (see https://github.com/pisa-engine/pisa/commit/2c459738fc23393c5f5009dc5b71e4b57d4f058d#diff-51da00fc61477e7d898e77928ab18333) is causing the algorithm to duplicate memory as it recurses (as it should), but the memory of the partition it recursed from remains in-use. 

- If my hypothesis is correct, I think we should be able to free the memory of the 'parent' partition once we recurse? So each time a partition is "done", we split and call two new threads which build their local storage and set up, and then we free the caller's memory.

- Related to #422

- I admit that this requires further investigation. However, correctness still seems good, as I can reproduce earlier results with similar indexes (eg, a CIFF gov2 index gives similar BPI to the ECIR paper).

**Comment by JMMackenzie** [comment]
A quick update - The BP process seems to be much slower than what we reported in the ECIR paper now. I think we have introduced some issues along the line. Matthias is currently exploring this further and will provide an update soon.-

**Comment by amallia** [comment]
I think you are right. It was probably introduced in https://github.com/pisa-engine/pisa/pull/378. Either we fix it quickly or it is probably safer to revert the PR since BP is quite an important piece.

**Comment by elshize** [comment]
@JMMackenzie isn't the point of the thread local storage is that it should keep the memory from the top layers. But it should reuse it instead of allocating more. I looked at the code and I have no idea where the problem would be. Any idea what part you think is being copied?

The thread local object is created once at the beginning of the algorithm and then passed as references. The only place I imagine could be broken is `clear_or_init` but no idea what. I'll look into the TBB docs to see if I'm missing something. Let me know if any of you have some more detailed ideas/suggestions.

**Comment by elshize** [comment]
Actually, I found a bug that probably causes it. The created object wasn't actually passed down the tree but rather was created over and over again. Check #424
